name: culti_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  spring_button: ^2.0.0
  dropdown_button2: ^2.3.9
  syncfusion_flutter_sliders: ^22.2.12
  dio: ^5.3.3
  shared_preferences: ^2.2.2
  get_it: ^7.6.4
  fluttertoast: ^8.2.2
  provider: ^6.0.5
  esp_smartconfig: ^1.1.11
  lottie: ^2.2.0
  wifi_iot: ^0.3.18
  permission_handler: ^10.2.0
  location: ^4.4.0
  mqtt_client: any
  day_night_time_picker: ^1.3.0+1
  flutter_picker: ^2.1.0
  network_info_plus: ^5.0.3
  simple_wifi_info: ^1.0.2
  intl: ^0.18.0
  system_date_time_format: any
  flutter_blue_plus: ^1.32.8
  loading_animation_widget: ^1.2.1
  flutter_bounceable: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lotti/
    - assets/menu/

  fonts:
    - family: Mon
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
